apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  timeout: 10m
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp
  releaseName: openmfp
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
    - name: istio-istiod
      namespace: istio-system
    - name: crossplane
      namespace: crossplane-system
  values:
    components: # TODO: remove when semver 0.0.238 is released
      example-content:
        enabled: true