apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp
  releaseName: openmfp
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
    - name: infra
      namespace: openmfp-system
  values:
    global:
      imagePullSecret: ghcr-credentials
      istio:
        enabled: true
    components:
      example-content:
        enabled: true
      portal:
        enabled: true
    portal:
      virtualService:
        hosts:
          - portal.openmfp.local
