apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  timeout: 10m
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp
  releaseName: openmfp
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
    - name: istio-istiod
      namespace: istio-system
    - name: crossplane
      namespace: crossplane-system
  values:
    global:
      imagePullSecret: ghcr-credentials
      istio:
        enabled: true
        gateway:
          name: gateway
    components:
      example-content:
        enabled: true
    example-content:
      istio:
        enabled: true
        virtualService:
          hosts:
            - "*"
          matchers:
            - match:
              - uri:
                  prefix: /ui/
    portal:
      baseDomains:
        - "localhost"
      cookieDomain: "localhost"
      http:
        protocol: http
      virtualService:
        hosts:
          - "*"
      validWebcomponentUrls: ".?"
      environment: local
      featureToggles: "enableSessionAutoRefresh=true"
      developmentLandcsape: "true"
      frontendPort: 8000
      importContent: false
      trust:
        openmfp:
          baseDomains: "localhost"
          discoveryEndpoint: ""
          authDomain: http://localhost:8000/keycloak/realms/openmfp/protocol/openid-connect/auth
          tokenUrl: http://openmfp-keycloak/keycloak/realms/openmfp/protocol/openid-connect/token
          oidcClientSecretName: openmfp-client
          loginAudience: openmfp
          secretKeyRef: attribute.client_secret
    infra:
      crossplane:
        enabled: true
      istio:
        enabled: true
        gateway:
          annotations: {}
          apiVersion: networking.istio.io/v1
          name: gateway
          selector:
            istio: gateway
          servers:
            - port:
                number: 8000
                name: http
                protocol: HTTP
              hosts:
                - "*"
    keycloak:
      istio:
        enabled: true
        virtualservice:
          hosts: [ "*" ]
        https:
          enabled: false
      crossplane:
        enabled: true
        realm:
          registrationAllowed: true
          name: openmfp
          displayName: OpenMFP
        identityProviders: { }

      keycloak:
        httpRelativePath: "/keycloak/"
        logging:
          level: DEBUG
        auth:
          adminUser: keycloak-admin
          existingSecret: keycloak-admin
          passwordSecretKey: secret
        resourcesPreset: none
        postgresql:
          nameOverride: postgresql-keycloak
          auth:
            username: keycloak
            existingSecret: ""
          primary:
            resourcesPreset: none

      keycloakConfig:
        url: http://openmfp-keycloak.openmfp-system.svc.cluster.local/keycloak
        redirectUrls: [ "http://localhost:8000/callback*" ]
      domain:
        pathPrefix: "/keycloak"
      service:
        port: 80
        name: openmfp-keycloak
