apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp
  releaseName: openmfp
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
    - name: infra
      namespace: openmfp-system
  values:
    global:
      imagePullSecret: ghcr-credentials
    components:
      infra:
        enabled: false
      kcp:
        enabled: false
      account-operator:
        enabled: false
      account-ui:
        enabled: false
      example-crd-gateway:
        enabled: false
      iam-service:
        enabled: false
      modular-models-operator:
        enabled: false
      openfga:
        enabled: false
    keycloak:
      externalSecrets:
        enabled: false
      crossplane:
        enabled: true
    example-ui:
      istio:
        enabled: true
        gateway:
          name: gateway
        virtualService:
          hosts:
            - "*"
          matchers:
            - match:
                - uri:
                    exact: /ui/example-content
                - uri:
                    prefix: /ui/example-content/

    example-resources:
      contentConfigurations:
        providers: true
      contentProtocolDomain: http://localhost:8000
    portal:
      virtualService:
        hosts:
          - "*"
