apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openmfp
  releaseName: openmfp
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
    - name: infra
      namespace: openmfp-system
  values:
    global:
      imagePullSecret: ghcr-credentials
      istio:
        enabled: true
    components:
      example-content:
        enabled: false
      portal:
        enabled: true
    portal:
      baseDomains:
        - "localhost"
      cookieDomain: "localhost"
      http:
        protocol: http
      virtualService:
        hosts:
          - "*"
      crdGatewayApiUrl: "http://localhost:8000/example-gateway/graphql"
      validWebcomponentUrls: ".?"
      environment: local
      featureToggles: "enableSessionAutoRefresh=true"
      developmentLandcsape: "true"
      frontendPort: 8000
      importContent: false
      trust:
        openmfp:
          baseDomains: "localhost"
          discoveryEndpoint: ""
          authDomain: http://localhost:8000/keycloak/realms/openmfp/protocol/openid-connect/auth
          tokenUrl: http://keycloak/keycloak/realms/openmfp/protocol/openid-connect/token
          oidcClientSecretName: openmfp-client
          loginAudience: openmfp
          secretKeyRef: attribute.client_secret
    infra:
      crossplane:
        enabled: true
      istio:
        enabled: true
        gateway:
          annotations: {}
          apiVersion: networking.istio.io/v1
          name: gateway
          selector:
            istio: gateway
          servers:
            - port:
                number: 8000
                name: http
                protocol: HTTP
              hosts:
                - "*"
