apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: openmfp
  namespace: openmfp-system
spec:
  interval: 5m
  url: oci://ghcr.io/openmfp/helm-charts/openmfp
  ref:
    # renovate: datasource=docker registryUrl=https://ghcr.io depName=ghcr.io/openmfp/helm-charts-priv/openmfp
    semver: 0.35.180
  secretRef:
    name: ghcr-credentials
