defaults:

  # -- service port
  port: 8080

  certManager:
    # -- toggle to enable/disable cert-manager
    enabled: false

  # -- imagePullSecret is the name of the secret that holds the docker registry credentials
  imagePullSecret: "github"

  # -- imagePullPolicy is the policy to use when pulling images for all charts
  imagePullPolicy: Always

  deployment:
    resources:
      # -- cpu and memory limits for the deployment
      limits:
        cpu: "100m"
        memory: "512Mi"
      # -- cpu and memory requests for the deployment
      requests:
        cpu: "40m"
        memory: "50Mi"
    # -- maxSurge
    maxSurge: 5
    # -- maxUnavailable
    maxUnavailable: 0
    # -- deployment strategy
    strategy: RollingUpdate
    # -- deployment revision history limit
    revisionHistoryLimit: 3

  health:
    # -- health port
    port: 8081
    # -- health period
    periodSeconds: 10
    # -- readiness probe parameters
    readiness:
      path: "/readyz"
      initialDelaySeconds: 5
      periodSeconds: 10
    # -- liveness probe parameters
    liveness:
      path: "/healthz"
      failureThreshold: 1
    # -- startup probe parameters
    startup:
      path: "/readyz"
      failureThreshold: 30

  metrics:
    # -- metrics port
    port: 8080
