apiVersion: v2
name: infra
description: A Helm chart for Kubernetes
type: application
version: 0.57.3
appVersion: "1.16.0"

dependencies:
  - name: common
    version: 0.1.6
    repository: oci://ghcr.io/openmfp/helm-charts
