version: '3'

vars:
  LOCAL_BIN: bin
  CHARTS:
    sh: "ls charts/ | sed 's/^/charts\\//g' | paste -sd ',' -"
tasks:
  ## Development
  lint:
    deps: []
    cmds:
      - "ct lint --target-branch main --validate-maintainers=false --charts={{.CHARTS}}"
  package:
    cmds:
      - helm package ./charts/openmfp
  helmtest:
    cmds:
      - "for chart in $(echo {{.CHARTS}} | tr ',' ' '); do helm unittest $chart; done"
  test:
    deps:
      - task: helmtest
  update:
    cmds:
      - "for chart in $(echo {{.CHARTS}} | tr ',' ' '); do helm dependency update $chart; done"
  validate:
    cmds:
      - task: lint
      - task: package
      - task: test