version: '3'

vars:
  LOCAL_BIN: bin
  CHARTS:
    sh: "ls charts/ | sed 's/^/charts\\//g' | paste -sd ',' -"
tasks:
  ## Setup
  setup:kube-lint:
    internal: true
    cmds:
      - mkdir -p $(pwd)/{{.LOCAL_BIN}}
      - test -s {{.LOCAL_BIN}}/kube-linter || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest
      - chmod +x $(pwd)/{{.LOCAL_BIN}}/kube-linter
  ## Development
  lint:
    deps: []
    cmds:
      - "ct lint --target-branch main --validate-maintainers=false --charts={{.CHARTS}}"
  package:
    cmds:
      - helm package ./charts/openmfp
  helmtest:
    cmds:
      - "for chart in $(echo {{.CHARTS}} | tr ',' ' '); do helm unittest $chart; done"
  test:
    deps:
      - task: helmtest
  update:
    cmds:
      - "for chart in $(echo {{.CHARTS}} | tr ',' ' '); do helm dependency update $chart; done"
  validate:
    cmds:
      - task: lint
      - task: package
      - task: test
  vulnerability:
    deps:
      - task: setup:kube-lint
    cmds:
      - "{{.LOCAL_BIN}}/kube-linter lint \"charts/\" --format \"plain\""