apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/openmfp
  - ../../components/openmfp-crds
  - ../../components/registry

patches:
- path: patch-openmfp.yaml
- path: patch-openmfp-crds.yaml
