apiVersion: v2
name: account-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.11
appVersion: "0.54.0"
dependencies:
  - name: account-operator-crds
    version: 0.0.2
    condition: crds.enabled
    repository: file://../account-operator-crds
  - name: common
    version: 0.1.3
    repository: file://../common
