# The image configuration for the Extension Manager Operator
## @param image.name The image repository
## @param image.tag The image tag
image:
  name: ghcr.io/openmfp/extension-manager-operator
  tag: 0.22.48

# The Custom Resource Definitions (CRDs) configuration
## @param crds.enabled Enable or disable the CRDs
crds:
  enabled: true

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

validationServer:
  # -- port for the validation server
  port: 8088
  # -- host for the validation VirtualService
  host: "*"

istio:
  # -- enable Istio VirtualService
  enabled: false