# The image configuration for the Extension Manager Operator
## @param image.name The image repository
## @param image.tag The image tag
image:
  name: ghcr.io/openmfp/extension-content-operator
  tag: 0.16.0

# The Custom Resource Definitions (CRDs) configuration
## @param crds.enabled Enable or disable the CRDs
crds:
  enabled: true

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
