apiVersion: v2
name: openmfp-crds
description: A chart containing CRD Definitions for OpenMFP
type: application
version: 0.0.12
appVersion: "0.0.0"

dependencies:
  - name: account-operator-crds
    version: 0.1.9
    repository: oci://ghcr.io/openmfp/helm-charts
    condition: components.account-operator-crds.enabled
  - name: extension-manager-operator-crds
    version: 0.1.6
    repository: oci://ghcr.io/openmfp/helm-charts
    condition: components.extension-manager-operator-crds.enabled
