apiVersion: v2
name: openmfp-crds
description: A chart containing CRD Definitions for OpenMFP
type: application
version: 0.0.1
appVersion: "0.0.0"

dependencies:
  - name: account-operator-crds
    version: 0.1.5
    repository: oci://ghcr.io/openmfp/helm-charts
    condition: components.account-operator-crds.enabled