{{- if .Values.istio.enabled -}}
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: {{ include "entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "entity.name" . }}
  mtls:
    mode: STRICT
{{- end -}}