{{- if .Values.istio.enabled -}}
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: {{ include "entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "entity.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end -}}