kind: Service
apiVersion: v1
metadata:
  name: {{ include "entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "entity.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: ClusterIP
