istio:
  virtualservice:
    # -- istio virtual service hosts
    hosts: [auth.openmfp.org]

# -- debug mode
debug: false

crossplane:
  # -- toggle to enable/disable crossplane
  enabled: false

  # -- crossplane provider config
  providerConfig:
    # -- name of the client
    name: keycloak-provider-config
    # -- client namespace
    namespace: openmfp-system

  # -- crossplane realm config
  realm:
    # -- realm name
    name: openmfp
    # -- realm display name
    displayName: OpenMFP
    # -- realm registration allowed
    registrationAllowed: false

  clients:
    openmfp:
      # -- name of the client
      name: OpenMFP
      # -- valid redirect uris for the client
      validRedirectUris:
        # -- keycloak callback url
        - http://localhost:8000/callback*
  trustedAudiences: []

  # -- crossplane identity providers config
  identityProviders:
    # -- sap IDP
    sap:
      # -- authorization URL
      authorizationUrl: https://login.microsoftonline.com/42f7676c-f455-423c-82f6-dc2d99791af7/oauth2/v2.0/authorize
      # -- token URL
      tokenUrl: https://login.microsoftonline.com/42f7676c-f455-423c-82f6-dc2d99791af7/oauth2/v2.0/token
      # -- user info URL
      issuer: https://login.microsoftonline.com/42f7676c-f455-423c-82f6-dc2d99791af7/v2.0
      # -- client id
      clientId: 82b4c72c-ff99-4df6-ba4f-fb634d1fc491
      # -- client secret
      clientSecretRef:
        # -- secret name
        name: sap-client-secret
        # -- secret namespace
        namespace: openmfp-system
        # -- secret key
        key: client-secret
      # -- user info URL
      clientSecretRemoteRef: dxp-core-team/manual-secrets/sap-client-secret

# -- configuration passed to the child 'keyclaok' chart
# https://github.com/bitnami/charts/tree/main/bitnami/keycloak
keycloak:
  # -- keycloak environment variables (raw)
  extraEnvVars: |
    - name: KEYCLOAK_USER
      value: keycloak-admin
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin
          key: secret
  # -- configuration for the postgresql sub-chart
  postgresql:
    # -- authorization configuration
    auth:
      # -- existing secret name
      existingSecret: ""
      secretKeys:
        # -- user password key
        userPasswordKey: password
        # -- admin password key
        adminPasswordKey: password

keycloakConfig:
  # -- url of the keycloak server
  url: http://keycloak-http.openmfp-system.svc.cluster.local:8080
  userRegistration:
    # -- toggle to enable/disable user registration
    enabled: true
  # -- redirect urls
  redirectUrls: []
  # -- realm configuration
  realm:
    # -- realm name
    name: master
  # -- client configuration
  client:
    # -- client name
    name: openmfp
    # -- target secret options
    targetSecret:
      # -- secret name
      name: portal-client-secret-openmfp
      # -- secret namespace
      namespace: openmfp-system
    # -- token lifespan
    tokenLifespan: 3600
  # -- admin user configuration
  admin:
    username:
      # -- username
      value: keycloak-admin
    # -- admin password
    password:
      valueFrom:
        secretKeyRef:
          # -- name of the secret containing the password
          name: keycloak-admin
          # -- key of the password in the secret
          key: secret

# -- service configuration
service:
  # -- service name
  name: keycloak
  # -- service port
  port: 8080

# -- domain configuration
domain:
  # -- domain name
  name: openmfp.org
  # -- path prefix
  pathPrefix: ""

# -- job configuration
job:
  # -- job ServiceAccount name
  serviceAccount: keycloak-client-creation
  # -- custom job annotations
  annotations:
    argocd.argoproj.io/hook: PostSync

# -- external secrets configuration
externalSecrets:
  # -- keycloak admin secret
  keycloakAdminRemoteRef: dxp-core-team/manual-secrets/keycloak-admin
  # -- postgres admin secret
  postgres-adminRemoteRef: dxp-core-team/manual-secrets/postgres-admin-password
