apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: keycloak
  releaseName: keycloak
  values:
    global:
      imagePullSecrets: 
        - "ghcr-credentials"
    crossplane:
      enabled: true
    debug: true
    istio:
      enabled: true
      virtualservice:
        hosts: [auth.openmfp.org]
    service:
      port: 8080
