apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: openmfp-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: keycloak
  releaseName: keycloak
  values:
    global:
      imagePullSecrets: 
        - "ghcr-credentials"
    debug: true
