apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: openmfp-system
spec:
  timeout: 10m
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: keycloak
  releaseName: keycloak
  dependsOn:
    - name: openmfp-crds
      namespace: openmfp-system
    - name: istio-istiod
      namespace: istio-system
    - name: crossplane
      namespace: crossplane-system
  values:
    global:
      imagePullSecrets: 
        - "ghcr-credentials"
      externalSecrets:
        enabled: false
    istio:
      enabled: true
      virtualservice:
        hosts: ["*"]
      https:
        enabled: false
    crossplane:
      enabled: true
      realm:
        registrationAllowed: true
        name: openmfp
        displayName: OpenMFP
      identityProviders: {}

    keycloak:
      httpRelativePath: "/keycloak/"
      logging:
        level: DEBUG
      auth:
        adminUser: keycloak-admin
        existingSecret: keycloak-admin
        passwordSecretKey: secret
      resourcesPreset: none
      postgresql:
        nameOverride: postgresql-keycloak
        auth:
          username: keycloak
          existingSecret: ""
        primary:
          resourcesPreset: none

    keycloakConfig:
      url: http://keycloak.openmfp-system.svc.cluster.local/keycloak
      redirectUrls: ["http://localhost:8000/callback*"]
    domain:
      pathPrefix: "/keycloak"
    service:
      port: 80
      name: keycloak
