{{- if eq (include "common.hasNestedKey" (dict "Values" .Values "key" "externalSecrets.enabled")) "true" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: account-operator-sa-kubeconfig
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: environment-store
    kind: SecretStore
  target:
    name: account-operator-sa-kubeconfig
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: {{ .Values.externalSecrets.accountOperatorSaKubeconfig }}
        property: kubeconfig
        conversionStrategy: Default
{{ end }}
