apiVersion: {{ .Values.gateway.apiVersion }}
kind: Gateway
metadata:
  name: {{ .Values.gateway.name}}
  namespace: {{ .Release.Namespace }}
{{- if .Values.gateway.annotations }}
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
{{ .Values.gateway.selector | toYaml | indent 4 }}
  servers:
{{ toYaml .Values.gateway.servers | indent 4 }}