{{- if eq (include "common.getKeyValue" (dict "Values" .Values "key" "istio.enabled")) "true" -}}
apiVersion: {{ .Values.istio.networking.apiVersion }}
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name}}
  namespace: {{ .Release.Namespace }}
{{- if .Values.istio.gateway.annotations }}
  annotations:
    {{- toYaml .Values.istio.gateway.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
{{ .Values.istio.gateway.selector | toYaml | indent 4 }}
  servers:
{{ toYaml .Values.istio.gateway.servers | indent 4 }}
{{- end -}}
