{{- if and .Values.kcp.enabled .Values.kcp.host -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: kcp-workspaces
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.kcp.host }}
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
{{- end -}}
