{{- if (.Values.keycloak).enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: auth
spec:
  hosts:
  {{- .Values.keycloak.hosts | toYaml | nindent 2 }}
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
{{- end -}}
