{{- if (.Values.auth).host -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: auth
spec:
  hosts:
  - {{ .Values.auth.host }}
  - login.microsoftonline.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
{{- end -}}
