{{- if and .Values.webhooks.enabled .Values.webhooks.register -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "common.entity.name" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "common.entity.name" . }}-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: {{ include "common.entity.name" . }}-webhook.{{ .Release.Namespace }}.svc:9443/mutate-core-openmfp-io-v1alpha1-account
  failurePolicy: Fail
  name: maccount.kb.io
  rules:
  - apiGroups:
    - core.openmfp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - accounts
  sideEffects: None
{{- end -}}