{{- if .Values.webhooks.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "entity.name" . }}-selfsigned-issuer
  namespace: {{ .Release.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "entity.name" . }}-serving-cert
  namespace: {{ .Release.namespace }}
spec:
  dnsNames:
  - {{ include "entity.name" . }}-webhook.{{ .Release.Namespace }}.svc
  - {{ include "entity.name" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ include "entity.name" . }}-webhook-server-cert
{{- end -}}
