{{- if .Values.webhooks.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.entity.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    service: {{ include "common.entity.name" . }}
    control-plane: controller-manager
{{- end -}}
