apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.revisionHistoryLimit") }}
  selector:
    matchLabels:
      {{- include "common.labelMatcher" . | indent 6 }}
  template:
    spec:
      {{- include "common.container.securityContext" . | indent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
        {{- include "common.commonArgs" . | indent 8 }}
        {{- include "common.extraArgs" . | nindent 10 }}
      env:
        {{- include "common.extraEnvs" . | nindent 8 }}
      volumeMounts:
        {{- include "common.extraVolumeMounts" . | nindent 8 }}
      volumes:
        {{- include "common.extraVolumes" . | nindent 8 }}
