apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.revisionHistoryLimit") }}
  selector:
    matchLabels:
      service: {{ include "common.entity.name" . }}
  template:
    spec:
      {{ include "common.container.securityContext" . | nindent 6 }}
      containers:
        - image: {{ include "common.image" . }}
          imagePullPolicy: {{ include "common.imagePullPolicy" . }}
          name: manager
          ports:
          {{ include "common.PortsMetricsHealth" . | nindent 10 }}
          {{ include "common.operatorHealthAndReadyness" . | nindent 10 }}
          {{ include "common.resources" . | nindent 10 }}
          env:
          {{- include "common.basicEnvironment" . | nindent 12 }}
          {{- include "common.extraEnvs" . | nindent 12 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      volumes:
        {{- include "common.extraVolumes" . | nindent 8 }}
