image:
  # @param image.name The image repository
  name: ghcr.io/openmfp/account-operator
  # @param image.tag The image tag
  tag: latest

# @param crds.enabled Enable CRDs
crds:
  enabled: true

# @param webhooks.enabled Enable webhooks
# @param webhooks.certDir The directory for webhook certificates
webhooks:
  enabled: false
  certDir: /certs


# The deployment configuration
## @param deployment.specTemplate.annotations The annotations to add to the deployment template
## @param deployment.specTemplate.labels The labels to add to the deployment template
## @param deployment.revisionHistoryLimit The number of old ReplicaSets to retain to allow rollback
## @param deployment.resources.limits.cpu The maximum amount of CPU the container is allowed to use
## @param deployment.resources.limits.memory The maximum amount of memory the container is allowed to use
## @param deployment.resources.requests.cpu The amount of CPU requested for the container
## @param deployment.resources.requests.memory The amount of memory requested for the container
deployment:
  specTemplate:
    annotations: {}
    labels: {}
  revisionHistoryLimit: 3
  resources:
    limits:
      cpuOverride: 260m
      memoryOverride: 512Mi
    requests:
      cpuOverride: 150m
      memoryOverride: 128Mi

# The KCP configuration
## @param kcp.enabled Enable KCP
## @param kcp.virtualWorkspaceUrl The URL for the virtual workspace
kcp:
  enabled: false
  virtualWorkspaceUrl: ""

# The subroutines configuration
## @param subroutines.namespace.enabled Enable namespace subroutines
## @param subroutines.fga.enabled Enable FGA subroutines
## @param subroutines.fga.grpcAddr The gRPC address for FGA
## @param subroutines.fga.rootNamespace The root namespace for FGA
## @param subroutines.fga.objectType The object type for FGA
## @param subroutines.fga.parentRelation The parent relation for FGA
## @param subroutines.fga.creatorRelation The creator relation for FGA
## @param subroutines.extension.enabled Enable extension subroutines
## @param subroutines.extensionReady.enabled Enable extension ready subroutines
subroutines:
  namespace:
    enabled: true
  fga:
    enabled: true
    grpcAddr: ""
    rootNamespace: openmfp-root
    objectType: account
    parentRelation: parent
    creatorRelation: owner
  extension:
    enabled: true
  extensionReady:
    enabled: true

# @param kubeconfigSecret The secret for kubeconfig
kubeconfigSecret: ""
# @param logLevel The log level
logLevel: warn

## @param security.mountServiceAccountToken Mount the service account token
security:
  mountServiceAccountToken: false
