image:
  # -- The image repository
  name: ghcr.io/openmfp/account-operator
  # -- The image tag
  tag: latest

crds:
  # -- Enable CRDs
  enabled: true

webhooks:
  # -- Enable webhooks
  enabled: false
  # -- The directory for webhook certificates
  certDir: /certs

# -- The KCP configuration
kcp:
  # -- Enable KCP
  enabled: false
  # -- The URL for the virtual workspace
  virtualWorkspaceUrl: ""

subroutines:
  namespace:
    # -- Enable namespace subroutines
    enabled: true
  fga:
    # -- Enable FGA subroutines
    enabled: true
    # -- The gRPC address for FGA
    grpcAddr: ""
    # -- The root namespace for FGA
    rootNamespace: openmfp-root
    # -- The object type for FGA
    objectType: account
    # -- The parent relation for FGA
    parentRelation: parent
    # -- The creator relation for FGA
    creatorRelation: owner
  extension:
    # -- Enable extension subroutines
    enabled: true
  extensionReady:
    # -- Enable extension ready subroutines
    enabled: true

# -- The secret for kubeconfig
kubeconfigSecret: ""
# -- The log level
logLevel: warn

security:
  # -- Mount the service account token
  mountServiceAccountToken: false

deployment:
  specTemplate:
    # -- The annotations for the deployment
    annotations: {}
    # -- The labels for the deployment
    labels: {}
