image:
  name: ghcr.io/openmfp/account-operator
  tag: latest

imagePullSecret: "github"

crds:
  enabled: true

health:
  port: 8081

metrics:
  port: 8080

deployment:
  revisionHistoryLimit: 3
  resources:
    limits:
      cpu: 260m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 128Mi
