image:
  # @param image.name The image repository
  name: ghcr.io/openmfp/account-operator
  # @param image.tag The image tag
  tag: latest

# @param crds.enabled Enable CRDs
crds:
  enabled: true

# @param webhooks.enabled Enable webhooks
# @param webhooks.certDir The directory for webhook certificates
webhooks:
  enabled: false
  certDir: /certs


# The KCP configuration
## @param kcp.enabled Enable KCP
## @param kcp.virtualWorkspaceUrl The URL for the virtual workspace
kcp:
  enabled: false
  virtualWorkspaceUrl: ""

# The subroutines configuration
## @param subroutines.namespace.enabled Enable namespace subroutines
## @param subroutines.fga.enabled Enable FGA subroutines
## @param subroutines.fga.grpcAddr The gRPC address for FGA
## @param subroutines.fga.rootNamespace The root namespace for FGA
## @param subroutines.fga.objectType The object type for FGA
## @param subroutines.fga.parentRelation The parent relation for FGA
## @param subroutines.fga.creatorRelation The creator relation for FGA
## @param subroutines.extension.enabled Enable extension subroutines
## @param subroutines.extensionReady.enabled Enable extension ready subroutines
subroutines:
  namespace:
    enabled: true
  fga:
    enabled: true
    grpcAddr: ""
    rootNamespace: openmfp-root
    objectType: account
    parentRelation: parent
    creatorRelation: owner
  extension:
    enabled: true
  extensionReady:
    enabled: true

# @param kubeconfigSecret The secret for kubeconfig
kubeconfigSecret: ""
# @param logLevel The log level
logLevel: warn

## @param security.mountServiceAccountToken Mount the service account token
security:
  mountServiceAccountToken: false

deployment:
  specTemplate:
    annotations: {}
    labels: {}
