image:
  name: ghcr.io/openmfp/account-operator
  tag: latest

imagePullSecret: "github"

crds:
  enabled: true

webhooks:
  enabled: false
  certDir: /certs

# The health probe configuration
## @param health.port The port for the health probe
## @param health.periodSeconds The period in seconds for performing the probe
## @param health.readiness.path The path for the readiness probe
## @param health.readiness.initialDelaySeconds The initial delay in seconds before starting the readiness probe
## @param health.readiness.periodSeconds The period in seconds for performing the readiness probe
## @param health.liveness.path The path for the liveness probe
## @param health.liveness.failureThreshold The failure threshold for the liveness probe
## @param health.startup.path The path for the startup probe
## @param health.startup.failureThreshold The failure threshold for the startup probe
health:
  port: 8081
  # periodSeconds: 10
  # readiness:
  #   path: "/readyz"
  #   initialDelaySeconds: 5
  #   periodSeconds: 10
  # liveness:
  #   path: "/healthz"
  #   failureThreshold: 1
  # startup:
  #   path: "/readyz"
  #   failureThreshold: 30


metrics:
  port: 8080

deployment:
  specTemplate:
    annotations: {}
    labels: {}
  revisionHistoryLimit: 3
  resources:
    limits:
      cpu: 260m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 128Mi

kcp:
  enabled: false
  virtualWorkspaceUrl: ""

subroutines:
  namespace:
    enabled: true
  fga:
    enabled: true
    grpcAddr: ""
    rootNamespace: openmfp-root
    objectType: account
    parentRelation: parent
    creatorRelation: owner
  extension:
    enabled: true
  extensionReady:
    enabled: true

kubeconfigSecret: ""
logLevel: warn
