apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: openmfp-crds
  namespace: openmfp-system
spec:
  interval: 5m
  url: oci://ghcr.io/openmfp/helm-charts/openmfp-crds
  ref:
    # renovate: datasource=docker registryUrl=https://ghcr.io depName=ghcr.io/openmfp/helm-charts/openmfp-crds
    semver: 0.0.18
  secretRef:
    name: github
