{{- if .Values.contentConfigurations.home }}
apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: home
  namespace: {{ .Release.Namespace }}
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "overview",
        "creationTimestamp": "2025-01-30T08:00:00Z",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "entityType": "global",
                "pathSegment": "home",
                "hideFromNav": true,
                "defineEntity": {
                  "id": "main"
                },
                "children": [
                  {
                    "pathSegment": "overview",
                    "label": "Configuration examples overview",
                    "icon": "home",
                    "defineEntity": {
                      "id": "overview"
                    },
                    "compound": {
                      "renderer": {
                        "use": "grid",
                        "config": {
                          "columns": "1fr 1fr 1fr 1fr"
                        }
                      }
                    }
                  },
                  {
                    "pathSegment": "firstExample",
                    "hideFromNav": true,
                    "defineEntity": {
                      "id": "first"
                    },
                    "compound": {
                      "renderer": {
                        "use": "grid",
                        "config": {
                          "columns": "1fr 1fr 1fr 1fr"
                        }
                      }
                    }
                  },
                  {
                    "pathSegment": "secondExample",
                    "hideFromNav": false, 
                    "defineEntity": {
                      "id": "second"
                    }             
                  },
                  {
                    "pathSegment": "fourthExample",
                    "hideFromNav": true,
                    "defineEntity": {
                      "id": "fourth"
                    },
                    "compound": {
                    }
                  }
                ]
              },
              {
                "entityType": "main.overview::compound",
                "url": "https://luigiwebcomponents.gitlab.io/layouts/panelHeader.js",
                "context": {
                  "border": "shadow",
                  "title": "Welcome to OpenMFP Portal",
                  "description": "Click on tab in the left side navigation to open a showcase of particular features"
                },
                "layoutConfig": {
                  "row": "1",
                  "column": "1 / -1"
                }
              },
              {
                "entityType": "main.overview::compound",
                "url": "http://localhost:4200/main.js#showcase",
                "context": {
                },
                "layoutConfig": {
                  "row": "2",
                  "column": "1 / -1"
                },
                "webcomponent": {
                  "selfRegistered": true
                }
              },
              {
                "entityType": "main.first::compound",
                "url": "https://luigiwebcomponents.gitlab.io/layouts/panelHeader.js",
                "context": {
                  "border": "shadow",
                  "title": "{{firstExampleTitle}}",
                  "description": "{{firstExampleDescription}}"
                }
              },
              {
                "entityType": "main.second",
                "pathSegment": "secondExample",
                "url": "https://example.com/",
                "loadingIndicator": {
                  "enabled": false
                },
                "requiredIFramePermissions": {
                  "sandbox": [
                    "allow-forms",
                    "allow-modals",
                    "allow-popups",
                    "allow-popups-to-escape-sandbox",
                    "allow-same-origin",
                    "allow-scripts",
                    "allow-download"
                  ],
                  "allow": [
                    "clipboard-read",
                    "clipboard-write"
                  ]
                }
              },
              {
                "entityType": "main.fourth::compound",
                "url": "http://localhost:4200/main.js#account-overview",
                "context": {
                  "title": "Showcase"
                },
                "layoutConfig": {
                  "row": "1",
                  "column": "1 / -1"
                },
                "webcomponent": {
                  "selfRegistered": true
                }
              }                           
            ],
            "texts": [
              {
                "locale": "",
                "textDictionary": {
                  "firstExampleTitle": "Definition of an Entity",
                  "firstExampleDescription": "Entity is basic building block of configuration."
                }
              }
            ]
          }
        }
      }
    contentType: json
{{- end }}