{{- if .Values.contentConfigurations.ui.enabled }}
apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: {{ include "common.entity.name" . }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  remoteConfiguration:
    url: {{ .Values.contentConfigurations.ui.url }}
    contentType: json
{{- end }}

{{- if .Values.contentConfigurations.wc.enabled }}
---
apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: {{ include "common.entity.name" . }}-wc
  namespace: {{ .Release.Namespace }}
spec:
  remoteConfiguration:
    url: {{ .Values.contentConfigurations.wc.url }}
    contentType: json
{{- end }}