{{- if .Values.contentConfigurations.home }}
apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: home
  namespace: {{ .Release.Namespace }}
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "overview",
        "creationTimestamp": "2022-05-17T11:37:17Z",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "entityType": "global",
                "pathSegment": "home",
                "hideFromNav": true,
                "defineEntity": {
                  "id": "main"
                },
                "children": [
                  {
                    "pathSegment": "overview",
                    "label": "Overview",
                    "icon": "home",
                    "defineEntity": {
                      "id": "overview"
                    },
                    "compound": {
                      "renderer": {
                        "use": "grid",
                        "config": {
                          "columns": "1fr 1fr 1fr 1fr"
                        }
                      }
                    }
                  }
                ]
              },
              {
                "entityType": "main.overview::compound",
                "url": "https://luigiwebcomponents.gitlab.io/layouts/panelHeader.js",
                "context": {
                  "border": "shadow",
                  "title": "Welcome to OpenMFP Portal",
                  "description": " "
                },
                "layoutConfig": {
                  "row": "1",
                  "column": "1 / -1"
                }
              }
            ]
          }
        }
      }
    contentType: json
{{- end }}