apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  labels:
    app: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.maxSurge") }}
      maxUnavailable: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.maxUnavailable") }}
  revisionHistoryLimit: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.revisionHistoryLimit") }}
  selector:
    matchLabels:
      app: {{ include "common.entity.name" . }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | indent 8 }}
    spec:
      {{- include "common.pod.securityContext" . | indent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
      {{- include "common.container.securityContext" . | indent 8 }}
        ports:
        {{- include "common.ports" . | nindent 10 }}
        env:
          {{- include "common.basicEnvironment" . | nindent 10 }}
          - name: PORT
            value: "{{ include "common.getKeyValue" (dict "Values" .Values "key" "port") -}}"
        volumeMounts:
          {{- include "common.extraVolumeMounts" . | nindent 8 }}
          - name: cache-volume
            mountPath: /var/cache/nginx
            readOnly: false
          - name: tmp-volume
            mountPath: /tmp
            readOnly: false
          - name: run-volume
            mountPath: /var/run
            readOnly: false
      volumes:
        {{- include "common.extraVolumes" . | nindent 8 }}
        - name: tmp-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}