apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  labels:
    app: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.maxSurge") }}
      maxUnavailable: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.maxUnavailable") }}
  revisionHistoryLimit: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.revisionHistoryLimit") }}
  selector:
    matchLabels:
      app: {{ include "common.entity.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "common.entity.name" . }}
    spec:
      serviceAccountName: {{ include "common.entity.name" . }}
      {{- include "common.spec.securityContext" (dict "Values" .Values) | nindent 6 }}
      containers:
      - name: {{ include "common.entity.name" . }}
        image: {{ .Values.image.name }}:{{ .Chart.AppVersion }}
        imagePullPolicy: {{ include "common.getKeyValue" (dict "Values" .Values "key" "imagePullPolicy") }}
        {{- include "common.container.securityContext" (dict "Values" .Values "Release" .Release) | nindent 8 }}
        env:
          - name: PORT
            value: "{{ include "common.getKeyValue" (dict "Values" .Values "key" "port") -}}"
        {{- include "common.resources" . | nindent 8 -}}
        {{- include "common.ports" (dict "Values" .Values) | nindent 8 }}
        volumeMounts:
          - name: tmp-volume
            mountPath: /var/cache/nginx
            readOnly: false
          - name: run-volume
            mountPath: /var/run
            readOnly: false
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}