{{- if eq (include "common.getNestedValue" (dict "Values" .Values "key" "istio.enabled")) "true" -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - {{ .Release.Namespace }}/{{ include "common.getKeyValue" (dict "Values" .Values "istio.gateway.name") }}
  hosts:
    {{- .Values.istio.virtualService.hosts | toYaml | nindent 2}}
  http:
  {{- .Values.istio.virtualService.matchers | toYaml | nindent 2 }}
    route:
      - destination:
          host: {{ include "common.entity.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8080
{{- end -}}