apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: micro-frontend-iframe-example
  namespace: {{ .Release.Namespace }}
spec:
  remoteConfiguration:
    url: http://localhost:4400/assets/showcase-examples/secondExample.json
    contentType: json