apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: configuration-examples-overview
  namespace: openmfp-system
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "configuration-examples-overview",
        "creationTimestamp": "2025-02-05T08:00:00Z",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "entityType": "global",
                "pathSegment": "home",
                "hideFromNav": true,
                "defineEntity": {
                  "id": "main"
                },
                "children": [
                  {
                    "pathSegment": "overview",
                    "label": "Configuration examples overview",
                    "icon": "home",
                    "defineEntity": {
                      "id": "overview"
                    },
                    "compound": {
                      "renderer": {
                        "use": "grid",
                        "config": {
                          "columns": "1fr 1fr 1fr 1fr"
                        }
                      }
                    }
                  },
                  {
                    "pathSegment": "firstExample",
                    "hideFromNav": true,
                    "defineEntity": {
                      "id": "first-example"
                    },
                    "compound": {
                      "renderer": {
                        "use": "grid",
                        "config": {
                          "columns": "1fr 1fr 1fr 1fr"
                        }
                      }
                    }
                  },
                  {
                    "pathSegment": "secondExample",
                    "virtualTree": true,
                    "navigationContext": "showcase",
                    "url": "http://localhost:4400/index.html#/showcase",
                    "loadingIndicator": {
                      "enabled": false
                    },
                    "requiredIFramePermissions": {
                      "sandbox": [
                        "allow-forms",
                        "allow-modals",
                        "allow-popups",
                        "allow-popups-to-escape-sandbox",
                        "allow-same-origin",
                        "allow-scripts",
                        "allow-download"
                      ],
                      "allow": [
                        "clipboard-read",
                        "clipboard-write"
                      ]
                    } 
                  },
                  {
                    "pathSegment": "fourthExample",
                    "hideFromNav": true,
                    "defineEntity": {
                      "id": "fourth-example"
                    },
                    "compound": {
                    }
                  }
                ]
              },
              {
                "entityType": "main.overview::compound",
                "url": "https://luigiwebcomponents.gitlab.io/layouts/panelHeader.js",
                "context": {
                  "border": "shadow",
                  "title": "Welcome to OpenMFP Portal",
                  "description": "Click on Show Example button to preview particular feature."
                },
                "layoutConfig": {
                  "row": "1",
                  "column": "1 / -1"
                }
              },
              {
                "entityType": "main.overview::compound",
                "url": "http://localhost:4200/main.js#showcase",
                "context": {
                },
                "layoutConfig": {
                  "row": "2",
                  "column": "1 / -1"
                },
                "webcomponent": {
                  "selfRegistered": true
                }
              }                                      
            ]
          }
        }
      }
    contentType: json