{{- if .Values.kcp.enabled -}}
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.openmfp.io
spec:
  latestResourceSchemas:
  - v241024-b5d9cd8.accounts.core.openmfp.io
status: {}
{{- end -}}
