{{- if .Values.kcp.enabled -}}
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.openmfp.io
spec:
  latestResourceSchemas:
  - v241024-b5d9cd8.accounts.core.openmfp.io
  permissionClaims:
    - group: ""
      resource: namespaces
      all: true
    - group: tenancy.kcp.io
      resource: workspaces
      identityHash: 007c0af6df73d2ac93c0ce21d99b413d87a6e599aa4f4f7d3f32fbbcd17d505e
      all: true
    - group: tenancy.kcp.io
      resource: workspacetypes
      identityHash: 007c0af6df73d2ac93c0ce21d99b413d87a6e599aa4f4f7d3f32fbbcd17d505e
      all: true
status: {}
{{- end -}}
