{{- if .Values.kcp.enabled -}}
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.openmfp.io
spec:
  latestResourceSchemas:
  - v241029-1a02f92.accounts.core.openmfp.io
  permissionClaims:
    - group: ""
      resource: namespaces
      all: true
    - group: tenancy.kcp.io
      resource: workspaces
      identityHash: {{ .Values.kcp.identityHash }}
      all: true
    - group: tenancy.kcp.io
      resource: workspacetypes
      identityHash: {{ .Values.kcp.identityHash }}
      all: true
status: {}
{{- end -}}
