---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 5m
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: 1.22.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-base

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: 1.22.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-istiod
  dependsOn:
    - name: istio-base
      namespace: istio-system
  values:
    pilot:
      cni:
        enabled: true
    # excludeNamespaces:
    #   - istio-system
    #   - kube-system
    # chained: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: 1.22.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-gateway
  dependsOn:
    - name: istio-istiod
      namespace: istio-system
  values:
    defaults:
      service:
        type: NodePort
        ports:
          - name: http
            port: 8000
            nodePort: 30000
          - name: https
            port: 8443
            nodePort: 31000
          - name: status-port
            port: 15021
            nodePort: 32000

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cni
      version: 1.24.2
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-cni
  dependsOn:
    - name: istio-base
      namespace: istio-system

