apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ include "common.getKeyValue" (dict "Values" .Values "key" "deployment.revisionHistoryLimit") }}
  selector:
    matchLabels:
      service: {{ include "common.entity.name" . }}
  template:
    metadata:
      labels:
        service: {{ include "common.entity.name" . }}
      {{- if ((.Values.deployment).template).labels }}
      {{ .Values.deployment.template.labels | toYaml | nindent 8 }}
      {{- end }}
      annotations:
        sidecar.istio.io/inject: "{{ (include "common.istioEnabled" .) }}"
      {{- if ((.Values.deployment).template).annotations }}
      {{ .Values.deployment.template.annotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "common.entity.name" . }}
      containers:
        - args:
          - operator
          - --leader-elect
          - --log-level={{ .Values.logLevel }}
          - '--health-probe-bind-address=:{{ include "common.getKeyValue" (dict "Values" .Values "key" "health.port") }}'
          image: {{ .Values.image.name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ include "common.imagePullPolicy" . }}
          name: manager
          {{ include "common.security" . | nindent 10 }}
          ports:
          {{ include "common.PortsMetricsHealth" . | nindent 10 }}
          {{ include "common.operatorHealthAndReadyness" . | nindent 10 }}
          {{ include "common.resources" . | nindent 10 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
