apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      service: {{ include "common.entity.name" . }}
  template:
    metadata:
      labels:
        service: {{ include "common.entity.name" . }}
      {{- if ((.Values.deployment).template).labels }}
      {{ .Values.deployment.template.labels | toYaml | nindent 8 }}
      {{- end }}
      annotations:
        sidecar.istio.io/inject: "{{ (include "common.istioEnabled" .) }}"
      {{- if ((.Values.deployment).template).annotations }}
      {{ .Values.deployment.template.annotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "common.entity.name" . }}
      containers:
        - args:
          - operator
          - --leader-elect
          - --log-level={{ .Values.logLevel }}
          - "--health-probe-bind-address=:{{ .Values.health.port }}"
          image: {{ .Values.image.name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ include "common.imagePullPolicy" . }}
          name: manager
          {{ include "common.security" . | nindent 10 }}
          ports:
          - containerPort: {{ .Values.metrics.port }}
            name: metrics
            protocol: TCP
          - name: health-port
            containerPort: {{ .Values.health.port }}
            protocol: TCP
          {{ include "common.operatorHealthAndReadyness" . | nindent 10 }}
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
