apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: providers
  namespace: openmfp-system
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "overview",
        "creationTimestamp": "2022-05-17T11:37:17Z",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "pathSegment": "marketplace",
                "label": "Marketplace",
                "entityType": "main",
                "loadingIndicator": {
                  "enabled": false
                },
                "keepSelectedForChildren": true,
                "url": "http://content.localhost:8000/ui/example-content/index.html#/global-catalog",
                "children": [
                  {
                    "pathSegment": ":id",
                    "url": "http://content.localhost:8000/ui/example-content/index.html#/catalog-item/:id",
                    "hideFromNav": true,
                    "label": "Service Details"
                  }
                ]
              },
              {
                "pathSegment": "capabilities",
                "label": "Marketplace",
                "entityType": "main.account",
                "loadingIndicator": {
                  "enabled": false
                },
                "keepSelectedForChildren": true,
                "url": "http://content.localhost:8000/ui/example-content/index.html#/global-catalog",
                "children": [
                  {
                    "pathSegment": ":id",
                    "url": "http://content.localhost:8000/ui/example-content/index.html#/catalog-item/:id",
                    "hideFromNav": true,
                    "label": "Service Details"
                  }
                ]
              },
              {
                "entityType": "main.overview::compound",
                "url": "http://content.localhost:8000/ui/wc/main.js#root-overview",
                "context": {
                  "title": "Resource Overview"
                },
                "layoutConfig": {
                  "row": "2",
                  "column": "1 / -1"
                },
                "webcomponent": {
                  "selfRegistered": true
                }
              },
              {
                "entityType": "main.account.dashboard::compound",
                "url": "http://content.localhost:8000/ui/wc/main.js#account-overview",
                "context": {
                  "title": "Resource Overview"
                },
                "layoutConfig": {
                  "row": "2",
                  "column": "1 / -1"
                },
                "webcomponent": {
                  "selfRegistered": true
                }
              }
            ]
          }
        }
      }
    contentType: json
---
apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  name: home
  namespace: openmfp-system
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "overview",
        "creationTimestamp": "2022-05-17T11:37:17Z",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "entityType": "global",
                "pathSegment": "home",
                "hideFromNav": true,
                "defineEntity": {
                  "id": "main"
                },
                "children": [
                  {
                    "pathSegment": "overview",
                    "label": "Overview",
                    "icon": "home",
                    "defineEntity": {
                      "id": "overview"
                    },
                    "compound": {
                      "renderer": {
                        "use": "grid",
                        "config": {
                          "columns": "1fr 1fr 1fr 1fr"
                        }
                      }
                    }
                  }
                ]
              },
              {
                "entityType": "main.overview::compound",
                "url": "https://luigiwebcomponents.gitlab.io/layouts/panelHeader.js",
                "context": {
                  "border": "shadow",
                  "title": "Welcome to ApeirORA Portal",
                  "description": " "
                },
                "layoutConfig": {
                  "row": "1",
                  "column": "1 / -1"
                }
              },
              {
                "entityType": "main.account",
                "pathSegment": "dashboard",
                "label": "Dashboard",
                "defineEntity": {
                  "id": "dashboard"
                },
                "compound": {
                  "renderer": {
                    "use": "grid",
                    "config": {
                      "columns": "1fr 1fr 1fr 1fr"
                    }
                  }
                }
              },
              {
                "entityType": "main.account.dashboard::compound",
                "url": "https://luigiwebcomponents.gitlab.io/layouts/panelHeader.js",
                "context": {
                  "border": "shadow",
                  "title": "Account Level Dashboard",
                  "description": "Comprehensive account overview dashboard for an account running inside an ApeiroRA instance"
                },
                "layoutConfig": {
                  "row": "1",
                  "column": "1 / -1"
                }
              }
            ]
          }
        }
      }
    contentType: json
