cors:
  enabled: false
  allowedHeaders: "*"
  allowedOrigins: "*"

image:
  name: ghcr.io/openmfp/kubernetes-graphql-gateway
  pullPolicy: IfNotPresent

kcp:
  enabled: true

gateway:
  port: 8080
  healthCheck:
    enabled: true
    port: 3389
  metricsPort: 8081
  graphiql: true
  logLevel: trace
  shouldImpersonate: true
  usernameClaim: email
  resources:
    limits:
      cpu: 1000m
      memory: 840Mi
    requests:
      cpu: 250m
      memory: 700Mi

listener:
  apiExportName: kcp.io
  port: 8090
  healthCheck:
    enabled: true
    port: 3390
  metricsPort: 8091
  resources:
    limits:
      cpu: 1000m
      memory: 840Mi
    requests:
      cpu: 250m
      memory: 700Mi

deployment:
  maxUnavailable: 0
  maxSurge: 5
  revisionHistoryLimit: 3
  replicas: 1


sentry:
  environment: dev

istio:
  enabled: true
  gateway:
    name: gateway

virtualService:
  pathPrefix: /kubernetes-graphql-gateway/
  hosts:
    - "*"
  httpRules:
    - name: default
      cors:
        allowHeaders:
          - "*"
        allowMethods:
          - GET
          - POST
        allowOrigins:
          - regex: .*

resources:
  limits:
    cpu: 2000m # We have spikes up to 2 cores
    memory: 1680Mi # let's make it 20% more than requests
  requests:
    cpu: 500m
    memory: 1400Mi

kubeConfig:
  createSecret: false
  enabled: false
  secretName: "kcp-root-kubeconfig"

extraEnvs: []
extraVolumes: []
extraVolumeMounts: []
