localDevelopment: true

cors:
  enabled: false
  allowedHeaders: "*"
  allowedOrigins: "*"

image:
  name: ghcr.io/openmfp/kubernetes-graphql-gateway
  pullPolicy: IfNotPresent

kcp:
  enabled: false

gateway:
  port: 8083
  healthCheck:
    enabled: true
    port: 3389
  metricsPort: 8081
  graphiql: true
  logLevel: trace
  shouldImpersonate: true
  usernameClaim: email

listener:
  enabled: true
  port: 8090
  healthCheck:
    enabled: true
    port: 3390
  metricsPort: 8091

imagePullSecret: ghcr-credentials

deployment:
  maxUnavailable: 0
  maxSurge: 5

sentry:
  environment: dev

istio:
  enabled: true
  gateway:
    name: gateway

virtualService:
  pathPrefix: /kubernetes-graphql-gateway/
  hosts:
    - "*"
  httpRules:
    - name: default
      cors:
        allowHeaders:
          - "*"
        allowMethods:
          - GET
          - POST
        allowOrigins:
          - regex: .*

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 320Mi

kubeConfig:
  createSecret: true
  content: |-
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1USXlOekV3TlRNeU9Wb1hEVE0wTVRJeU5URXdOVE15T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1dhCk91V0dWQVlFSGdLVVRUZ1IrN1pQeG5nNjVnWXhKWlFKVEFqR1g0YUgzeHBEd0dWYWVhUlZCeGE2OEdwM25YOFkKNHh0NGVmL3kwc2gyRHk4NWJQS2VaSWE2K1hiZ2xtZGtIWWR0bk14SHJ6KzFhOCt1TUhpS2t6am5KeThZS01mVApCVGsrQVFYNkw1cy9WNm90MzhDVjA0ZE5FNEJ3TXQ3UjZMQzh5dUpXM1U3NTRvTlNWMy92d2k1aFJadWtZUWFUCjRHeUJXNWIyNGVSaE11Q1NHLzV4bFVHMWcySHlGS3FpbllYOSsyTWdtdGVCbWh1SzI1dDB1U2I2RU9ZYzJHajQKU3dkOXplc0VUSysyNXFrZk1ncml1MHVSZ013azYvVC84ZmE5QWxiYW16N1FiL0NVR0JVRzZKQm1JQnlYdmpzbwphdmFBcDVLZi9hRUgvTmROdi9zQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEaVE5V0N6TjB6T2xvOEgzbXFxSm1GU2REek9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS3RCdXo0Z1lRdlhHYjdVV3p2MQp4VkgyZGZoT04rYTZWUFNmVjJVd3B2WTAxNElRNVVPdytXK0l1U1dQVFUwZk5tZEhsNjNxWEMreFlDSmllRFA3CmhWQ3lzMXhBeU1JbkZEVS9za2ZyZnlOd1lLMHpqNHpaN1VUcm5SanpQNU4yNXllU0VxV08zdC8rcjF2TlNvTTEKbk1nVEwyRXdzaktLQVZiTHhkeHNQVklld1pGc0dEVC9iM2UxclZPKzFDb0oydi9YMlNtc3hjSlRuOFkzN2srVApraUFmQ202aDBzdHNCcjMvVUlWUUdsamxleTdwU2VPSVMxaU45MHE3UGNUTFlLdWlqclFCakxEcFByejdmZ2ZYCkw5dlFzL3lyRzI0SmhGajhFclUybndGRXA0UGoyVXB5cFhnVDRVL200NFBMYzBic3U4THhlNG55ZHVZS1VCSW0KeVZBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          server: https://127.0.0.1:55226
        name: kind-kcp
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZFA4NWVYZ0Vsb0V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UY3hNalF5TURsYUZ3MHpOVEF6TVRVeE1qUTNNRGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQyUXdza2d1b004L04zUE5NVXZ2MllkZm9ic09BelN4WE45ZUUvUTU4aWRUN2FnblNUc1YrTTBoWm4KaVMwaGpJTHVVanp0MlNreDZ4MGtpeTZRMjYzaEh4TnhFcTRLMTlINmwzaHBLczhSY0l6UC9FL2dlT05PN3YyTAprRjIrYTl4QnFid3NpcFpSQ1lNdzBIWDA1R01iWmk0VmVyZlVrUWlJMkJ6eEVITUE1bkREaXRua0x6Z1QvMlQ3CndiVDd1K0wvRTJNWmpmYXppS1RIRUREZDV1ZEJaUGFQblZRckR4SElJWlg5c1NxRlU5VFgrNisvR0w0aU1xS2EKRDNwaTdNZU9ZZ042d1ZZc05uRHU3c2JsM3ZLVXZrbTkxWXEwVHh0MXlhS0N2T01ENUQydk5rZkRpVjAxcHIvNgpaL1pYK0UralpsK1AvdjBYN0hTYXBjNURGemh4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUWXg0ekxVd2xzVExmaEN6cStiVDZaSlJOckdUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2MzeDRuaC9hQQoxS1VGRmY5UTJaQi9aUFU4UDdMTGxVbU9aNFQ2M0tERlc0QktzVDVDQVpmYktpclhZZ1Q5aHhsY0VlSUNzNTMxCm5KZ3RKMHVXcFptYmc0dSs1czRSY0tmc01yOEZQMXowN3R2aytHYUYvUGp0YWl2SmFvUGRPbytSeXJORE1WZzEKV0Z0bGt1bUJkWWV6aWtJaUg2SjYzbkZyWnFMVnczRSs0ZDJPai95MzZ3MDFuZWt1ZWdObjA1UkJVRFBNUU1YQwpSOHJFd1JwSXNCbWNCL1pGUHVRZmE4djI3L2V5ZkF1bzRwYUdUdHlwR004WG83K3h3NlUzTkJ3SHhkaDhGOEg1CjhBcWVaZGZ3YUlSaHlCbm1kZjJ4a2xvSm9XZEpIeVF2OXJHM3dzcER0ZFBpaHdaeExVVXVuekhpbGVsb3JmVEEKcVlRdDV0NjJ5cXhQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          server: https://127.0.0.1:49798
        name: kind-kind
    contexts:
      - context:
          cluster: kind-kcp
          user: kind-kcp
        name: kind-kcp
      - context:
          cluster: kind-kind
          user: sa
        name: kind-sa
      - context:
          cluster: kind-kind
          user: kind-kind
        name: kind-kind
    current-context: kind-kind
    kind: Config
    preferences: {}
    users:
      - name: kind-kcp
        user:
          client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJYXl5RUx1TVVJL1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1qY3hNRFV6TWpsYUZ3MHlOVEV5TWpjeE1EVXpNekJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXMxZUt0dnVzaWdma3BDSHgKRFpOeHovc0x2OXkzWWtZeW9xb24rZURUamJwd2xQZGdzY1pSNFZBbEVJZndLTUZFZFgrWURWK21CdWtEZHZyeAp1a24xcVowejd2b3dQZll0NjdwRThTZldFVDNDTmJMaWhiV3B3WjB6NXVxQXhqQ1hPODlTN3JiWTdxNDlvL1ZXCjhFWUxFZEM4eGQ1VkJObWFnbTQ0QVk3dlhERkptczFjQjdTZkZzaFhqQUo5ZzVrSlNISHpzUzBrN2NWYlZnY2YKNjAwcjFSZ0E4emFLQ2pwSXQ4YkVPSCtXT1NZWFNiU1pTZnVsREJGVHV4MUxJb3hxMWNoU3dxd1JMWUovV2svZwpDekduNitCNmd3cEYxV2pXMCttaC9tazRqbmZjMzgzM3VSZjYxZFZiNzBtWHdocmI2RFRZM051M0NFZmx5eDJjCnJKSDN5UUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRNGtQVmdzemRNenBhUEI5NXFxaVpoVW5ROAp6akFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBYjZKMlYxNVRiZ2tOMzBkRE5aQWZYQ2pkbkR2ak1pTm1kWEJpCnhxYk1xdTJETGh5czY1Vkp2TG45cGZBUWdPRU4weWFDS1Z4UW5Yek5qb1VIZi81SWIyU05ycjQxejFMM0VRNFYKRlBwWWVUMjl2NkxwUS9QWXpPWlQyQllOSzdCeWNpUUtQZjRYVHhnMjVqRXREVndlUzN6bGNzb0x3N3hibWIzMgppa05jd0NRbkE4K3UyUVhPazNOTjZBcDhwZ1dKc1ZBWlJWZWUzblJOU3pMVVhHN3NFaGZXYWdaQjJRZ2hRRitvCnIzUmU0K010TndvNzZPRW03Q2xDWDlYMDVIbkdSd2Yrb0V2K2xwYmd4K3dBdUp1YUFlNkZmVWt4WmQ0WWhPVDcKT21WNUk4N0gyY3YyM0lVTVhTU09tNmVCWkEvY2FRQWttdXhJZjVNTDg1ZnUyRVVkMWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBczFlS3R2dXNpZ2ZrcENIeERaTnh6L3NMdjl5M1lrWXlvcW9uK2VEVGpicHdsUGRnCnNjWlI0VkFsRUlmd0tNRkVkWCtZRFYrbUJ1a0RkdnJ4dWtuMXFaMHo3dm93UGZZdDY3cEU4U2ZXRVQzQ05iTGkKaGJXcHdaMHo1dXFBeGpDWE84OVM3cmJZN3E0OW8vVlc4RVlMRWRDOHhkNVZCTm1hZ200NEFZN3ZYREZKbXMxYwpCN1NmRnNoWGpBSjlnNWtKU0hIenNTMGs3Y1ZiVmdjZjYwMHIxUmdBOHphS0NqcEl0OGJFT0grV09TWVhTYlNaClNmdWxEQkZUdXgxTElveHExY2hTd3F3UkxZSi9Xay9nQ3pHbjYrQjZnd3BGMVdqVzArbWgvbWs0am5mYzM4MzMKdVJmNjFkVmI3MG1Yd2hyYjZEVFkzTnUzQ0VmbHl4MmNySkgzeVFJREFRQUJBb0lCQVFDbUFjcXRScG1YeTJhaApaNm15WDJGaW00ZHN1ZW9tVmNSWlBoaHkvT0hXdDFXdkRxMjY0VkM1dDI0WHR6MWUvRWRhWEJscmg3WXZmMUZ0CnVTdzR2RzFoNjlvK3crZ1Q4dVRlNXpVWjVUNEtCNWpXREJnU25PM2VBcDRnaWNGWnMzREtORWNZSUxqOWR0d28KQU5uUTM0VXZvSUNjeUFqNnpGSnhtWVRPTEhqMFpENkU0N3pPTDhmWmN1R1JyQW1od05lUThiVnZFQ0U5U2VicQpLTWJNTTRaMVo0MGZWQ3pNbXVNQ3B1d1ZRSlY4NGIrSUlBRmpHbWJsUUtXVVdiUGNQWmprbUFpeFFjNEg3ajlHClRYTjRlOVN1eGhGdUZNV2RRMnpGRVhWWVdpeDFyLzhrTWw4V3pVTzZkSGN6cEpYdzBmZm9qQXpXakppSktaSXoKa3JuWHdhWGhBb0dCQU5lKzBTL3M4dC8wbjUvZ1A4c0dGRjVOUEczT2JDSW5XWGZOa0J6SE5kcVJ4U1IrakxpNAo1bEZYYkpJZ2pqNGNkMnFDVkQ2TTZOM2FhK21vaEtwR1RGcVhjTjhRL0l0OTRUK2JIcVVLWXh4QmhuVHIrWmNLCnkvQU4yT1MvZWJuSnR2SG0wU0FIWkF1MFNhL2RtelBydTdUT3pVVjhwdDNlL3JkMVQ3RHBhejdyQW9HQkFOVE4KNWREeDlLb2hNOGNsdnBrdUNaTUp3UThNV3pDeS94QS9ZRnIvSFVnY05GMk93UStJbUEreG1wU3dKVW54a3dwMApRd3RzZ2JSQmxTbjV3SWdPUGdRbDlwS3VHTGgwRDBaNnhuRGtjNXZiN3Q0Ymd4elc3a21ldmljYjA5TmUrNk93CktWdVdwSmkxRXlTWFFLRmtidGtSNUtxZ0V1UE9GNG85dnlVa3M3OGJBb0dBR3pwU3pqaWFRbGR1R2RCRVhNd00Kb0FZaFhUNVMrVkI4QXhtbldXcHV5b0hoSG9UMkg0MytTeis4VFFqY3lzdnU2anMraEpKbUJURytzc040MHNDQwpmR0JtZDFCK2Z1QkpJQ3praGpHMFptbUNuWmoyYS9DSjRtYnMrNW1LdEQ3WDN0bWhoT2hKNFF4RXpIUXNWVFluCi8xNm1HMkhxOFU5bVdDTHZCc1crcWpjQ2dZQkpDK1EzTk5hbkQzNldmWDVQVmw0eStzWXFSRE9KSStncHk1ZG4KcE9xSU5pWkRkeDBPRi9VYWJmeUJ6WFQvVE0wTWFad1o3OFVWK3UwWTI0SWJNY2hYNURBZmFXTlM3WVBRelpRUQpiRnJDeFZ2WklkaC9yY2RkdmYvSHJPV3BTSkZZUHIvemtHSXZpUGhwTndJWVpFRW9nZHZjTmRaR0hCZzRlN21CCkpuZ013UUtCZ0gwdTVkVzJ2VzlSL2hBdVBwTzc2RlNDdm1wNXBsaHd3bUtIWEcyMGhLMlZXSWZtUzlPeTFyM2EKV1pES0txeGpnMVV4R0RidkIzMHpBR2FiWk8zTG1hNGpFTmNaR1hIejNzQm03YlZXdWsxN2FPcHA0Wk9wYmsvVApmb1JIY2QyamhDVnVRcHo5ZWdhSjhXZGFQSHJ5bFpYWGhCVXJiQnZYN0ZMOUJuM2hKMEZ1Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
      - name: sa
        user:
          token: eyJhbGciOiJSUzI1NiIsImtpZCI6InlZWnMyR095RXVVX1FncWRET2ZOYTBUS1g0eHJCclVINzZVLW5qMThPdlUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM4MjU0OTkyLCJpYXQiOjE3MzgyNTEzOTIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZDZkNWFkMzMtNWQ0My00NDAwLTg4MjgtYTliODdmYTBkNjZlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InJlbGVhc2UtbmFtZS1leGFtcGxlLWNyZC1nYXRld2F5IiwidWlkIjoiOGI1ZDc3NTctZjhjOC00MTEyLWFmNjAtNGJjNGEyNjVmMDBhIn19LCJuYmYiOjE3MzgyNTEzOTIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnJlbGVhc2UtbmFtZS1leGFtcGxlLWNyZC1nYXRld2F5In0.RmeTaSworzYbmoo6gXalf2t-_itkzsPGT11On01WxFPtK66fyM1euK9t6Hl5Po25gI7obTemeHNA-sR1FpGQ7cSSUUTiebyMSOfhO2BFoaWkrUw5NkBF0VYQXl1_kujEdseO70M3Le24nRpm7k4kc99H3UCQNRFW1RJTojZSidYKn05wRS_56r2lA8T1gito8U-Ax5nvPXRX9A3A9nZ4mVpZ7kJ5kFraSqRyJ8m2nVkhMTl8klT_5EqFhL1Sk3HQ9S-Q576xCtvfmcpn9jnZUsruivdWHki2dKxcBIJQK5iZ479lnhpkL6Mcw75hYB2mIdlqs4nodAdkRZ4j_bfq-A
      - name: kind-kind
        user:
          client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJVDV0NXhZSjdWNXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UY3hNalF5TURsYUZ3MHlOakF6TVRjeE1qUTNNRGxhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQlVuNVcKb0VndmpaRGFxUURXeFVOc2kzVXU3a2xnQzh4dTlNWisxRnc0ejJVVFh4Q0FiZkx5UVg2bkE5Q1ptc0NkaUlWZQp2MzgzV25EaDQ3NDdreGhZMHVHRFNhV2UzeDNsdTZKUjVBbk5HbXRBQTlCYnVUV25yQ0c3dkZwdkpWVmVUYlRSCjZiVTFXVjZPc1RFMWJjNXhSS3NxY2djZU9QQm9HSzBJRFhZdXByUWJRTUxqTnJVcVlZMG9hM3gxVHJnMjZmM0cKVUgydld2ODNWZit0VFVSYUw3Q0J5UkdmZVd2NEgwRFRlWGY2T2JGTUJQSUdhbFAwTHRzcXdOazN2SFh5MGsxcwpxUkZjY29ZMExOOXdEaktBWjZDeGV0alZSNFVVakxxc0Y5VjZETzZzZDBxdU9QNi80T0pnN0c0Smo1dnk3TFFsCjBhQkRSOHJLUWFoUFNZWjFBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRk5qSGpNdFRDV3hNdCtFTApPcjV0UHBrbEUyc1pNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUURXNWp1SVJpT3ZQTy9NdlpxRzJZM2o5c01OCk9ZQ3M1RjN6ZU8zN1RLbDRWd2sxUWFlbDhvb0lvaWdLQ0Q2enc4N2RGR2tSYlZ5U3NHbXVHVVVUaVBjdkxoN2EKTFRIRHBIRzdBQjIrNk5BMzg2alYvdnI2VTg1ZWFwSDVJSmtnOC9zVVU3NWQrOXhza09WcmZXMU52aHdZQWhZeApKc2UrQk11VjlhZTdWOVhJbUV3SjZFVjd6dU5JK0RPWEdHTmdsM2pVTTcyRUU4UkZrcTdjV09DVnBDOXdaSXZ0CjhqN01UeFN0TUZqRUFDcTlPeklIM0xJYWY3a3doN1RoUEZXU1ppelRBc0QyZXYwUUVNZVJid1FvVGd1WWhhM0MKRVBIVUlmOVRMb0d2amtKbThVZE04dk9MWGxnOVZsU2lySS9XMGdXdlJNcmwweHgrdWorcE1pRTg1VWtiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBd1ZKK1ZxQklMNDJRMnFrQTFzVkRiSXQxTHU1SllBdk1idlRHZnRSY09NOWxFMThRCmdHM3k4a0YrcHdQUW1ackFuWWlGWHI5L04xcHc0ZU8rTzVNWVdOTGhnMG1sbnQ4ZDVidWlVZVFKelJwclFBUFEKVzdrMXA2d2h1N3hhYnlWVlhrMjAwZW0xTlZsZWpyRXhOVzNPY1VTcktuSUhIamp3YUJpdENBMTJMcWEwRzBEQwo0emExS21HTktHdDhkVTY0TnVuOXhsQjlyMXIvTjFYL3JVMUVXaSt3Z2NrUm4zbHIrQjlBMDNsMytqbXhUQVR5CkJtcFQ5QzdiS3NEWk43eDE4dEpOYktrUlhIS0dOQ3pmY0E0eWdHZWdzWHJZMVVlRkZJeTZyQmZWZWd6dXJIZEsKcmpqK3YrRGlZT3h1Q1krYjh1eTBKZEdnUTBmS3lrR29UMG1HZFFJREFRQUJBb0lCQUZQWlBOVER0aXR4NGxjRQpvRW1HeTZTanBCTFQ1VjFVSUxvclRvQ3FDTW5YSWtiUm42MmtncEFTV2lXRVlSQ09iMmFrVlB4d1lIUVl0UWMwCnFVamJsdDdIc0dvcUlqeVRGenVTTTJnRFdVRHRhWUVkWmx5eUt4UnJjMElqQXJKY1pmZCtDcVJWRW5SdUs3WUcKSW9yQzhweHNKVFZHdWRHZzdweW52enpUNGVOL1JoNkVuR0FxNzZPNFhGYnJsekxScVZ5enJsc2poZHdBcDc1aQpkNXJlcVFiUnlKUlFBendNZHZuWVBLR0ovVWRtOHFLZy9CVUQxblZRZG15TkhEVTNmanZpUURqbGc1ekxmN2gxCkhyMkxMWlFlMzFUZk0vekZYVWhVaHNjZFlBNllvZXZuclZQMjhzTTRObmhWV05CcHcwTm54NnZjNjZxNnBtUjAKWlczaTVFRUNnWUVBK25jYWZ6RUZTR2dWeXdWZmszcTkwS2V4OHc3SVJEZWcwWktDU2E3Tmlud05OY1ZGSHMzawpnSHU2c1N1bGNrQUw3OW1tYU5ENzBxaWlabkJRT3ZsNHAvNU9PNFBqbXFmeStMd2NFd25DSGFzKzQxZWFRSjZ2Ci82bU5mb3FTVE9wVzZndGV0SlV6YmE5WjUwZUJGTmJtNUNSdUt2MDZjU1VtMk1vZ3VEeitjQ1VDZ1lFQXhaZ2cKOFZpRUZjZlZyK1diYmwyQ1NURWhsc2hFUTVoSjlISUZlRk54VHVFWEpXYjE2cDlkdUkybGplYkI5U2xTV09xRwpHa1ZZcEpJanZtWUZPTTNPdy9SMUhtaVNNakZFdnl5ajkxeXJtOHZWYmJyZWFwYWFkT21VakFjZE8wbnZJV1lzCklLa2l3aERIbUFTRWh6K2ZhdVI4cHgzQ2hGUDkzWUJsY0l6OWhCRUNnWUVBblA4N1pLN2RtTjFsaTdUNmkvOU0KTEJaeHZPRnZOeE9IZ3RaTFJOU0ZrbURnQnV4NHZ5NWdKUWxwcE5TdkNFYU5OUE5CRkVLckZ3a05neGl6c2NQZQpsYThhYXNQcFQzQW5KVE1FaGdwLzJ3a1VpbnpHKytwOGQ4MVlIQkhRVXRZeFZOTjdzY1kwVG5TejdmMHNORnZnCnJ2RUcvWHR0dnE2REF6RHdBWXg2RU9FQ2dZRUF0VnZFSU1DVnUwZ0hvY0trdnMrazNYankwMnBNL1oyeGcyT0UKRWNURW94bUdIUlk3Y0hXRmwvYXFsV3ZQYWkzYkh6RmlsSXBCcWd0WU0xR0FTWHJjNUk1alVOMjZFY2VXeWNFMwpYYnI0NTY1VzNyZzluS2RPYlRCVzM0OUlEVHIyK1RqR0Y5UWx5dW1MeU1PY3dHWnM4N2R6a2crR2tkNWxqQUJsCkdzRE5qNEVDZ1lFQXRIYjdLcHZXZW5iR0hTZjYybytsVTlQSEptNjdtaG5qWFJVYTZNaURWOGg5a0QrU1NxdGwKeXI0b29SVng1RGNrTnpFZ2I5UW95N3hkcnpJc1VnY3g2eHNKUVorN29RQTNUS2FKOGJMVnhzb083SVQ3czBNUAovL2JlS1grblBIR2FqRGl6RTBQSGIzZlRucUtrVCtwb2QrS1JIdmZSU1BYdk93TVdDTktSOHNFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=


extraEnvs: []
extraVolumes: []
extraVolumeMounts: []
