apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.openmfp.org
spec:
  latestResourceSchemas:
  - v250516-0b27c30.accountinfos.core.openmfp.org
  - v250305-70de32b.accounts.core.openmfp.org
  permissionClaims:
  - all: true
    resource: namespaces
  - all: true
    group: tenancy.kcp.io
    identityHash: '{{ .Values.kcp.identityHash }}'
    resource: workspaces
  - all: true
    group: tenancy.kcp.io
    identityHash: '{{ .Values.kcp.identityHash }}'
    resource: workspacetypes
status: {}
