image:
  # -- The image name
  name: ghcr.io/openmfp/example-content

istio:
  virtualService:
    hosts:
      - your-host.com
    matchers:
      - match:
          - uri:
              exact: /ui/example-content
          - uri:
              prefix: /ui/example-content/
