image:
  # -- The image name
  name: ghcr.io/openmfp/example-content

istio:
  virtualService:
    hosts:
      - your-host.com
    matchers:
      - match:
          - uri:
              exact: /ui/example-content
          - uri:
              prefix: /ui/example-content/

contentConfigurations:
  # -- This content configuration enables a basic homepage in the portal
  ui:
    enabled: true
    url: http://localhost:8000/ui/example-content/ui/assets/config.json
  wc:
    enabled: true
    url: http://localhost:8000/ui/example-content/ui/assets/config.json

contentProtocolDomain: https://example-content.some-domain.com
