image:
  # -- The image name
  name: ghcr.io/openmfp/example-content

istio:
  enabled: true
  virtualService:
    hosts:
      - "*"
    matchers:
      - match:
        - uri:
            prefix: /ui/example-content

contentConfigurations:
  # -- This content configuration enables a basic homepage in the portal
  ui:
    enabled: true
    url: http://localhost:8000/ui/example-content/ui/assets/config.json
    internalUrl: http://openmfp-example-content.openmfp-system.svc.cluster.local:8080/ui/example-content/ui/assets/config.json
# Set internal url especially for local a setup where the url is not reachable from within the cluster
#    internalUrl: null
  wc:
    enabled: true
    url: http://localhost:8000/ui/example-content/wc/assets/config.json
    internalUrl: http://openmfp-example-content.openmfp-system.svc.cluster.local:8080/ui/example-content/wc/assets/config.json
# Set internal url especially for local a setup where the url is not reachable from within the cluster
#    internalUrl: null

contentProtocolDomain: https://example-content.some-domain.com
