image:
  name: ghcr.io/openmfp/example-content
  pullPolicy: IfNotPresent
  pullSecret: github

istio:
  enabled: true
  gateway:
    name: gateway
  virtualService:
    hosts:
      - your-host.com
    matchers:
      - match:
          - uri:
              exact: /ui/example-content
          - uri:
              prefix: /ui/example-content/
