name: Build account-operator Workflow
on:
  push:
    paths:
      - 'charts/account-operator-new/**'
      - '.github/workflows/account-operator-new.yaml'

jobs:
  pipeline:
    concurrency:
      group: account-operator-new-${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: account-operator-new
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit

  updateVersionFile:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [pipeline]
    uses: openmfp/gha/.github/workflows/job-update-version-file.yml@main
    secrets: inherit
    with:
      componentVersionKey: "account-operator-new"
      version: ${{ needs.pipeline.outputs.version }}