name: Verify Helm Docs up-to-date
on:
  - pull_request

jobs:

  chekc-statuses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/create-outputs@v0.0.0-fake
      id: test
    - uses: LouisBrunner/checks-action@v2.0.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: ${{ job.status }}
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}

  update-helm-docs:
    runs-on: ubuntu-latest
    needs: [chekc-statuses]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          fail-on-diff: false
          chart-search-root: charts/
          template-files: README.md.gotmpl
          git-push: true
          git-push-user-name: "openmfp-technical-user"
          git-push-user-email: "openmfp@gmail.com"
          git-commit-message: "chore: update Helm documentation"