name: Verify Helm Docs up-to-date
on:
  - pull_request

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          fail-on-diff: false
          chart-search-root: charts/
          template-files: README.md.gotmpl
          git-push: true
          git-push-user-name: "openmfp-technical-user"
          git-push-user-email: "openmfp@gmail.com"
          git-commit-message: "chore: update Helm documentation"