name: Check if helm-docs are up-to-date
on:
  - pull_request

jobs:

  check-helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          fail-on-diff: true
          chart-search-root: charts/
          template-files: README.md.gotmpl
          git-push: true
