name: Build infra Workflow
on:
  push:
    paths:
      - 'charts/infra/**'
      - '.github/workflows/infra.yaml'
      - '.ocm/component-constructor-chart-only.yaml'
  pull_request:
    paths:
      - 'charts/infra/**'
      - '.github/workflows/infra.yaml'

jobs:
  pipeline:
    concurrency:
      group: infra-${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: infra
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit

  ocm:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [pipeline]
    uses: openmfp/gha/.github/workflows/job-ocm.yml@switch-oci-repo
    secrets: inherit
    with:
      chartPath: charts/infra
      componentName: github.com/openmfp/infra
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml