name: Build Keycloak
on:
  push:
    paths:
      - 'charts/keycloak/**'
      - '.github/workflows/keycloak.yaml'
  pull_request:
    paths:
      - 'charts/keycloak/**'
      - '.github/workflows/keycloak.yaml'

jobs:
  pipeline:
    concurrency:
      group: keycloak-${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: keycloak
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit

  updateVersionFile:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [pipeline]
    uses: openmfp/gha/.github/workflows/job-update-version-file.yml@main
    secrets: inherit
    with:
      componentVersionKey: "keycloak"
      version: ${{ needs.pipeline.outputs.version }}