name: Test local setup
on:
  pull_request:
    branches:
      - '**'


jobs:
  kind-localsetup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: engineerd/setup-kind@v0.6.0
      with:
        version: "v0.24.0"

    - name: Run start.sh
      uses: actions/checkout@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./local-setup/scripts/start.sh


