name: Test local setup
on:
  pull_request:
    branches:
      - '**'


jobs:
  kind-localsetup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

     # Step 2: Install KIND
    - name: Install KIND
      run: |
          # For AMD64 / x86_64
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
          # For ARM64
          [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-arm64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 3: Verify KIND installation
    - name: Verify KIND installation
      run: kind version

    - name: Run start.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x /home/runner/work/helm-charts/helm-charts/local-setup/scripts/start.sh
        /home/runner/work/helm-charts/helm-charts/local-setup/scripts/start.sh


