name: Test local setup
on:
  pull_request:
    branches:
      - '**'


jobs:
  kind-localsetup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

     # Step 2: Install KIND
    - name: Install KIND
      run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 3: Verify KIND installation
    - name: Verify KIND installation
      run: kind version

    # - name: Run start.sh
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     ./local-setup/scripts/start.sh


