name: Test local setup
on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: localsetup-${{ github.ref }}
  cancel-in-progress: false

jobs:
  kind-localsetup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

     # Step 2: Install KIND
    - name: Install KIND
      run: |
          # For AMD64 / x86_64
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
          # For ARM64
          [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-arm64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 3: Verify KIND installation
    - name: Verify KIND installation
      run: kind version
    
    - name: Install HELM
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh


    - name: Install the gh cli
      uses: ksivamuthu/actions-setup-gh-cli@v3
      with:
        version: 2.24.3
    - run: |
        gh version


    - name: Run start.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GH_TOKEN: ${{ secrets.OPENMFP_PUBLISHER_PRIVATE_KEY }}
        GH_USER: ${{ github.repository_owner }}
      run: |
        chmod +x /home/runner/work/helm-charts/helm-charts/local-setup/scripts/start.sh
        /home/runner/work/helm-charts/helm-charts/local-setup/scripts/start.sh


