name: Build kubernetes-graphql-gateway
 Workflow
on:
  push:
    paths:
      - 'charts/kubernetes-graphql-gateway/**'
      - '.github/workflows/kubernetes-graphql-gateway.yaml'
  pull_request:
    paths:
      - 'charts/kubernetes-graphql-gateway/**'
      - '.github/workflows/kubernetes-graphql-gateway.yaml'

jobs:
  pipeline:
    concurrency:
      group: kubernetes-graphql-gateway-${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: kubernetes-graphql-gateway
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts,kcp=https://kcp-dev.github.io/helm-charts'
    secrets: inherit

  updateVersionFile:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [pipeline]
    uses: openmfp/gha/.github/workflows/job-update-version-file.yml@main
    secrets: inherit
    with:
      componentVersionKey: "kubernetes-graphql-gateway"
      version: ${{ needs.pipeline.outputs.version }}
