name: Build portal Workflow
on:
  push:
    paths:
      - 'charts/portal/**'
      - '.github/workflows/portal.yaml'
  pull_request:
    paths:
      - 'charts/portal/**'
      - '.github/workflows/portal.yaml'

jobs:
  pipeline:
    concurrency:
      group: portal-${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: portal
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit

  ocm:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [pipeline]
    uses: openmfp/gha/.github/workflows/job-ocm.yml@switch-oci-repo
    secrets: inherit
    with:
      chartPath: charts/portal
      componentName: github.com/openmfp/portal
