name: PR Checks workflow
on:
  pull_request:
    branches:
      - main

concurrency:
  group: localsetup-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  checkdiff:
    concurrency:
      group: common-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    outputs:
      helmcharts: ${{ steps.changed-chart-files.outputs.helmcharts_any_changed }}
    steps:
      - name: Get changed files for charts
        id: changed-chart-files
        uses: step-security/changed-files@v45
        with:
          files_yaml: |
            helmcharts:
              - charts/**

  pipeline:
    needs: checkdiff
    if: ${{ needs.checkdiff.outputs.helmcharts == 'false' }}
    concurrency:
      group: common-${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: common
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit
